import { describe, expect, it } from "vitest";
import {
  FAILURE_RULE_DESCRIPTIONS,
  type FailureAnalysisConclusion,
  type SpecificationContext,
} from "@apipilot/shared-domain";
import {
  FAILURE_ANALYSIS_PROMPT_FINGERPRINT,
  FAILURE_ANALYSIS_RESPONSE_VERSION,
  FAILURE_ANALYSIS_SYSTEM_PROMPT,
  buildFailureAnalysisPrompt,
  buildFailureAnalysisRequest,
  computeFailureAnalysisPromptFingerprint,
} from "../../../src/failureAnalysis/failureAnalysisPrompt";
import { buildEvidence } from "../../../src/failureAnalysis/buildEvidence";
import { collectRedactedValues } from "../../../src/failureAnalysis/redaction";
import { failedResult, rawCaptureWithSecrets, withRawCapture } from "../../fixtures/failureAnalysis/fixtures";

const unavailable: SpecificationContext = { status: "unavailable", reason: "not-generated-by-current-workflow" };
const downstream: FailureAnalysisConclusion = {
  kind: "likely-cause",
  cause: "downstream-service-issue",
  strength: "moderate",
  ruleId: "dependency-named-in-server-error",
  decidingEvidenceIds: ["E1", "E5"],
};
const insufficient: FailureAnalysisConclusion = { kind: "insufficient-evidence", reason: "no-rule-matched" };

function promptFor(context: SpecificationContext = unavailable, conclusion: FailureAnalysisConclusion = downstream, note?: string) {
  const result = withRawCapture(failedResult());
  const { evidence } = buildEvidence(result, context);
  return buildFailureAnalysisPrompt({
    requestMethod: result.requestMethod,
    requestName: result.requestName,
    evidence,
    specificationContext: context,
    conclusion,
    ...(note ? { note } : {}),
  });
}

describe("failureAnalysisPrompt v4 (research D8, D16)", () => {
  it("builds a JSON inference request with the feature's own system prompt and no timeout override", () => {
    const request = buildFailureAnalysisRequest(promptFor());

    expect(request).toMatchObject({
      contractVersion: 1,
      expectedOutputFormat: "json",
      maxOutputTokens: 256,
      systemPrompt: FAILURE_ANALYSIS_SYSTEM_PROMPT,
    });
    expect(request.timeoutMs).toBeUndefined();
    expect(request.requestId).toMatch(/^failure-[0-9a-f]{24}$/);
    expect(buildFailureAnalysisRequest(promptFor()).requestId).toBe(request.requestId);
  });

  it("is response version 4 (v3 was evaluated but never shipped)", () => {
    expect(FAILURE_ANALYSIS_RESPONSE_VERSION).toBe(4);
  });

  it("gives the model the rule-decided cause to explain, never a choice of causes", () => {
    const parsed = JSON.parse(promptFor()) as Record<string, unknown>;

    expect(parsed.responseVersion).toBe(4);
    expect(parsed.classification).toEqual({
      cause: "Potential downstream-service issue",
      rule: FAILURE_RULE_DESCRIPTIONS["dependency-named-in-server-error"],
    });
    expect(parsed.evidence).toEqual(expect.arrayContaining([expect.objectContaining({ id: "E1" })]));
    expect(parsed.allowedCauses).toBeUndefined();
    expect(parsed.examples).toBeUndefined();
  });

  it("states that no rule matched for insufficient evidence", () => {
    const parsed = JSON.parse(promptFor(unavailable, insufficient)) as { classification: Record<string, unknown> };
    expect(parsed.classification).toEqual({ cause: "none", rule: "No rule matched the recorded evidence." });
  });

  it("carries a placeholder answer format with no cause or confidence to copy", () => {
    const format = (JSON.parse(promptFor()) as { answerFormat: Record<string, unknown> }).answerFormat;

    expect(Object.keys(format).sort()).toEqual(["evidenceIds", "responseVersion", "steps", "summary"]);
    expect(format.responseVersion).toBe(4);
    expect(format.steps).toEqual([expect.any(String)]);
    expect(format).not.toHaveProperty("cause");
    expect(format).not.toHaveProperty("confidence");
  });

  it("passes a capacity note only when evidence was omitted for the prompt", () => {
    expect(JSON.parse(promptFor()).note).toBeUndefined();
    expect(JSON.parse(promptFor(unavailable, downstream, "Body excerpts were omitted.")).note).toBe("Body excerpts were omitted.");
  });

  it("states whether specification context exists", () => {
    const matched: SpecificationContext = {
      status: "matched",
      workflowId: "tgw-1",
      scenarioId: "s",
      scenarioName: "GET /users with valid input",
      scenarioCategory: "positive",
      operationPath: "/users",
      operationMethod: "GET",
      documentedStatusCodes: ["200"],
      requestEditedAfterGeneration: false,
      upstream: [],
    };
    expect(JSON.parse(promptFor()).specificationContextNote).toBe(
      "No specification context: this request was not generated by the current guided workflow.",
    );
    expect(JSON.parse(promptFor(matched)).specificationContextNote).toBe(
      'Generated from GET /users, scenario "GET /users with valid input".',
    );
  });

  it("never contains a value that redaction replaced", () => {
    const prompt = promptFor();
    for (const secret of collectRedactedValues(rawCaptureWithSecrets())) {
      expect(prompt).not.toContain(secret);
    }
  });

  it("pins the prompt text so every change bumps the response version (constitution XXIII)", () => {
    expect(
      computeFailureAnalysisPromptFingerprint(),
      "prompt changed: bump FAILURE_ANALYSIS_RESPONSE_VERSION and update the fingerprint",
    ).toBe(FAILURE_ANALYSIS_PROMPT_FINGERPRINT);
  });
});
