import { describe, expect, it } from "vitest";
import type { SpecificationContext } from "@apipilot/shared-domain";
import {
  FAILURE_ANALYSIS_PROMPT_FINGERPRINT,
  FAILURE_ANALYSIS_RESPONSE_VERSION,
  FAILURE_ANALYSIS_SYSTEM_PROMPT,
  buildFailureAnalysisPrompt,
  buildFailureAnalysisRequest,
  computeFailureAnalysisPromptFingerprint,
} from "../../../src/failureAnalysis/failureAnalysisPrompt";
import { buildEvidence } from "../../../src/failureAnalysis/buildEvidence";
import { collectRedactedValues } from "../../../src/failureAnalysis/redaction";
import { failedResult, rawCaptureWithSecrets, withRawCapture } from "../../fixtures/failureAnalysis/fixtures";

const unavailable: SpecificationContext = { status: "unavailable", reason: "not-generated-by-current-workflow" };

function promptFor(context: SpecificationContext = unavailable) {
  const result = withRawCapture(failedResult());
  const { evidence } = buildEvidence(result, context);
  return buildFailureAnalysisPrompt({
    requestMethod: result.requestMethod,
    requestName: result.requestName,
    evidence,
    specificationContext: context,
  });
}

describe("failureAnalysisPrompt (research D6, D8)", () => {
  it("builds a JSON inference request with the feature's own system prompt and no timeout override", () => {
    const request = buildFailureAnalysisRequest(promptFor());

    expect(request).toMatchObject({
      contractVersion: 1,
      expectedOutputFormat: "json",
      maxOutputTokens: 256,
      systemPrompt: FAILURE_ANALYSIS_SYSTEM_PROMPT,
    });
    expect(request.timeoutMs).toBeUndefined();
    expect(request.requestId).toMatch(/^failure-[0-9a-f]{24}$/);
    expect(buildFailureAnalysisRequest(promptFor()).requestId).toBe(request.requestId);
  });

  it("carries the response version, the evidence, the allowed causes and contrasting worked examples", () => {
    const parsed = JSON.parse(promptFor()) as Record<string, unknown>;

    expect(parsed.responseVersion).toBe(FAILURE_ANALYSIS_RESPONSE_VERSION);
    expect(parsed.evidence).toEqual(expect.arrayContaining([expect.objectContaining({ id: "E1" })]));
    expect(Object.keys(parsed.allowedCauses as object)).toEqual([
      "specification-mismatch",
      "environment-issue",
      "downstream-service-issue",
      "insufficient-evidence",
    ]);
    const examples = parsed.examples as Array<{ answer: { cause: string; steps: string[] } }>;
    // v1's single example was copied verbatim by the default model (evaluation.md), so the
    // examples must disagree with each other on cause.
    expect(new Set(examples.map((example) => example.answer.cause)).size).toBe(examples.length);
    expect(examples.some((example) => example.answer.cause === "insufficient-evidence")).toBe(true);
    for (const example of examples) {
      if (example.answer.cause !== "insufficient-evidence") expect(example.answer.steps.length).toBeGreaterThanOrEqual(1);
    }
  });

  it("states whether specification context exists", () => {
    const matched: SpecificationContext = {
      status: "matched",
      workflowId: "tgw-1",
      scenarioId: "s",
      scenarioName: "GET /users with valid input",
      scenarioCategory: "positive",
      operationPath: "/users",
      operationMethod: "GET",
      documentedStatusCodes: ["200"],
      requestEditedAfterGeneration: false,
      upstream: [],
    };
    expect(JSON.parse(promptFor()).specificationContextNote).toBe(
      "No specification context: this request was not generated by the current guided workflow.",
    );
    expect(JSON.parse(promptFor(matched)).specificationContextNote).toBe(
      'Generated from GET /users, scenario "GET /users with valid input".',
    );
  });

  it("never contains a value that redaction replaced", () => {
    const prompt = promptFor();
    for (const secret of collectRedactedValues(rawCaptureWithSecrets())) {
      expect(prompt).not.toContain(secret);
    }
  });

  it("pins the prompt text so every change bumps the response version (constitution XXIII)", () => {
    expect(
      computeFailureAnalysisPromptFingerprint(),
      "prompt changed: bump FAILURE_ANALYSIS_RESPONSE_VERSION and update the fingerprint",
    ).toBe(FAILURE_ANALYSIS_PROMPT_FINGERPRINT);
  });
});
