import { useEffect, useRef, useState, type Ref } from "react";
import {
  FAILURE_RULE_DESCRIPTIONS,
  type FailureAnalysis,
  type FailureAnalysisExplanation,
  type FailureAnalysisInProgress,
  type FailureCause,
  type FailureEvidence,
  type SpecificationContext,
  type SpecificationContextUnavailableReason,
  type UpstreamContext,
} from "@apipilot/shared-domain";
import {
  getFailureAnalysisInProgress,
  requestFailureAnalysis,
} from "../services/externalCollectionsClient";
import { strengthLabel } from "../utils/strengthLabel";
import { ErrorState } from "./ErrorState";
import { HttpMethodBadge } from "./HttpMethodBadge";
import { ProvenanceBadge } from "./ProvenanceBadge";
import { StatusBadge, type StatusTone } from "./StatusBadge";
import { BUTTON_STYLES } from "./controlStyles";

/** Matches the enhancement progress view's cadence (specs/030-ai-failure-analysis research D10). */
export const IN_PROGRESS_POLL_MS = 1_000;

const CAUSE_LABEL: Record<FailureCause, string> = {
  "specification-mismatch": "Potential specification mismatch",
  "environment-issue": "Potential environment issue",
  "downstream-service-issue": "Potential downstream-service issue",
};


export function unavailableContextText(reason: SpecificationContextUnavailableReason): string {
  switch (reason) {
    case "no-request-identity":
      return "This result was recorded before ApiPilot tracked which request produced it.";
    case "no-generated-collection":
      return "This session has no generated collection. Run a collection from the guided workflow's hand-off to see specification context.";
    case "not-generated-by-current-workflow":
      return "This request was not generated by the current guided workflow. Start from the guided workflow's hand-off to see specification context.";
    case "no-originating-scenario":
      return "This request was generated without a test scenario (for example an OAuth2 token request).";
  }
}

const OUTCOME_IN_RUN: Record<UpstreamContext["outcomeInRun"], { label: string; tone: StatusTone }> = {
  passed: { label: "Passed", tone: "success" },
  failed: { label: "Failed", tone: "danger" },
  "not-attempted": { label: "Not sent", tone: "neutral" },
  "not-in-run": { label: "Not in this run", tone: "neutral" },
};

function formatElapsed(ms: number): string {
  const seconds = Math.max(0, Math.floor(ms / 1_000));
  if (seconds < 60) return `${seconds} s`;
  return `${Math.floor(seconds / 60)} min ${seconds % 60} s`;
}

function ElapsedTime({ since }: Readonly<{ since: string }>) {
  const [now, setNow] = useState(() => Date.now());
  useEffect(() => {
    const timer = setInterval(() => setNow(Date.now()), 1_000);
    return () => clearInterval(timer);
  }, []);
  return <span className="font-mono text-xs text-muted">{formatElapsed(now - new Date(since).getTime())}</span>;
}

function EvidenceItem({ item }: Readonly<{ item: FailureEvidence }>) {
  return (
    <li className="flex flex-wrap items-baseline gap-2">
      <span className="font-mono text-xs text-muted">{item.id}</span>
      <span className="min-w-0 break-words">{item.text}</span>
      <span className="text-xs text-muted">
        {item.source === "specification-context" ? "from the specification" : "from the run"}
      </span>
    </li>
  );
}

function SpecificationContextSection({ context }: Readonly<{ context: SpecificationContext }>) {
  if (context.status === "unavailable") {
    return (
      <section aria-label="Specification context" className="space-y-1">
        <h5 className="text-xs font-semibold uppercase text-muted">Specification context</h5>
        <p>Specification context unavailable: {unavailableContextText(context.reason)}</p>
      </section>
    );
  }
  return (
    <section aria-label="Specification context" className="space-y-2">
      <h5 className="text-xs font-semibold uppercase text-muted">Specification context</h5>
      <p className="flex flex-wrap items-center gap-2">
        <HttpMethodBadge method={context.operationMethod} />
        <span className="font-mono text-xs">{context.operationPath}</span>
      </p>
      <p>
        Scenario: {context.scenarioName} ({context.scenarioCategory})
      </p>
      <p>
        Documented responses:{" "}
        {context.documentedStatusCodes.length > 0 ? context.documentedStatusCodes.join(", ") : "none"}
      </p>
      {context.requestEditedAfterGeneration && (
        <p className="text-warning-700 dark:text-warning-100">
          Note: this request was edited after generation, so it differs from the generated request.
        </p>
      )}
      {context.upstream.length > 0 && (
        <div className="space-y-1">
          <h6 className="text-xs font-semibold text-muted">Upstream requests</h6>
          <ul className="space-y-1">
            {context.upstream.map((entry) => {
              const outcome = OUTCOME_IN_RUN[entry.outcomeInRun];
              const where =
                entry.via === "integration-workflow" ? `Step ${(entry.stepPosition ?? 0) + 1}` : "Producer";
              return (
                <li
                  key={`${entry.via}-${entry.stepPosition ?? ""}-${entry.operationMethod}-${entry.operationPath}`}
                  className="flex flex-wrap items-center gap-2"
                >
                  <span>
                    {where}: {entry.operationMethod.toUpperCase()}{" "}
                    <span className="font-mono text-xs">{entry.operationPath}</span> ({entry.suppliedFields.join(", ")})
                    {" — "}
                    {outcome.label.toLowerCase()}
                  </span>
                  <StatusBadge label={outcome.label} tone={outcome.tone} />
                </li>
              );
            })}
          </ul>
        </div>
      )}
    </section>
  );
}

/**
 * The AI-written part (FR-007): the only part labelled as an AI inference. When it could not be
 * written, the reason is shown instead, and the rule-decided cause above still stands (FR-006).
 */
function ExplanationSection({ explanation }: Readonly<{ explanation: FailureAnalysisExplanation }>) {
  return (
    <section aria-label="AI explanation" className="space-y-2 rounded border border-border p-2">
      <div className="flex flex-wrap items-center gap-2">
        <ProvenanceBadge source="AI" />
        <span className="text-xs font-medium text-slate-700 dark:text-slate-300">
          AI inference, not a confirmed root cause
        </span>
      </div>
      {explanation.status === "available" ? (
        <>
          <p className="text-slate-700 dark:text-slate-300">{explanation.summary}</p>
          <section aria-label="Suggested next steps" className="space-y-1">
            <h5 className="text-xs font-semibold uppercase text-muted">Suggested next steps</h5>
            <ol className="list-decimal space-y-1 pl-5">
              {explanation.investigationSteps.map((step) => (
                <li key={step}>{step}</li>
              ))}
            </ol>
          </section>
        </>
      ) : (
        <p>
          <span className="font-semibold">AI explanation unavailable:</span> {explanation.message}
        </p>
      )}
    </section>
  );
}

function AnalysisView({
  analysis,
  headingRef,
}: Readonly<{ analysis: FailureAnalysis; headingRef: Ref<HTMLHeadingElement> }>) {
  const { conclusion, explanation } = analysis;
  const insufficient = conclusion.kind === "insufficient-evidence";
  // The evidence that decided the cause; for insufficient evidence, what the AI cited instead (FR-003).
  let shownIds: readonly string[] = [];
  if (conclusion.kind === "likely-cause") shownIds = conclusion.decidingEvidenceIds;
  else if (explanation.status === "available") shownIds = explanation.citedEvidenceIds;
  const shown = analysis.evidence.filter((item) => shownIds.includes(item.id));
  const other = analysis.evidence.filter((item) => !shownIds.includes(item.id));

  return (
    <div className="space-y-3" data-testid="failure-analysis-result">
      <section aria-label="Likely cause" className="space-y-1">
        <h4 ref={headingRef} tabIndex={-1} className="text-sm font-semibold text-slate-900 focus:outline-none dark:text-white">
          {insufficient ? "Not enough evidence to name a likely cause" : CAUSE_LABEL[conclusion.cause]}
        </h4>
        {conclusion.kind === "likely-cause" ? (
          <>
            <p className="flex flex-wrap items-center gap-2">
              <ProvenanceBadge source="RULE" />
              <span>Strength: {strengthLabel(conclusion.strength)}</span>
            </p>
            <p>{FAILURE_RULE_DESCRIPTIONS[conclusion.ruleId]}</p>
            <p className="text-xs text-muted">Decided by a fixed rule: a likely cause, not a confirmed root cause.</p>
          </>
        ) : (
          <p>No rule matched the recorded evidence.</p>
        )}
      </section>

      {shown.length > 0 && (
        <section aria-label={insufficient ? "Evidence cited" : "Evidence for this cause"} className="space-y-1">
          <h5 className="text-xs font-semibold uppercase text-muted">
            {insufficient ? "Evidence cited" : "Evidence for this cause"}
          </h5>
          <ul className="space-y-1">
            {shown.map((item) => (
              <EvidenceItem key={item.id} item={item} />
            ))}
          </ul>
        </section>
      )}

      <ExplanationSection explanation={explanation} />

      {other.length > 0 && (
        <details className="rounded border border-border p-2">
          <summary className="cursor-pointer text-xs font-semibold text-muted focus:outline-none focus-visible:ring-2 focus-visible:ring-brand-500">
            Other evidence considered ({other.length})
          </summary>
          <ul className="mt-2 space-y-1">
            {other.map((item) => (
              <EvidenceItem key={item.id} item={item} />
            ))}
          </ul>
        </details>
      )}

      <SpecificationContextSection context={analysis.specificationContext} />

      <p className="text-xs text-muted">
        Cause decided by rule set v{analysis.classificationProvenance.ruleSetVersion}
        {explanation.status === "available"
          ? `; explanation by ${explanation.provenance.aiModel} (${explanation.provenance.aiProvider})`
          : ""}
        , {new Date(analysis.analyzedAt).toLocaleString()}
      </p>
    </div>
  );
}

type AttemptError = { kind: "failed" | "busy"; message: string } | null;

/**
 * On-demand AI failure analysis for one failed result (specs/030-ai-failure-analysis FR-001,
 * FR-007, FR-016, SC-005). The parent owns which analyses are stored and whether any analysis is
 * in progress in the session; this panel starts a request, polls its phase while it is pending,
 * and renders whatever is stored.
 */
export function FailureAnalysisPanel({
  collectionId,
  runId,
  resultIndex,
  requestName,
  analysis,
  inProgress,
  onAnalysisChange,
  onInProgressChange,
}: Readonly<{
  collectionId: string;
  runId: string;
  resultIndex: number;
  requestName: string;
  analysis?: FailureAnalysis;
  inProgress: FailureAnalysisInProgress | null;
  onAnalysisChange: (analysis: FailureAnalysis) => void;
  /** `startedHere` tells the parent this panel is polling, so it need not poll too. */
  onInProgressChange: (inProgress: FailureAnalysisInProgress | null, startedHere: boolean) => void;
}>) {
  const [pending, setPending] = useState(false);
  const [error, setError] = useState<AttemptError>(null);
  const [settledCount, setSettledCount] = useState(0);
  const headingRef = useRef<HTMLHeadingElement>(null);
  const errorRef = useRef<HTMLDivElement>(null);

  const thisOne = inProgress !== null && inProgress.runId === runId && inProgress.resultIndex === resultIndex;
  const otherInProgress = inProgress !== null && !thisOne;

  useEffect(() => {
    if (!pending) return;
    const timer = setInterval(async () => {
      const result = await getFailureAnalysisInProgress();
      if (result.ok && result.inProgress) onInProgressChange(result.inProgress, true);
    }, IN_PROGRESS_POLL_MS);
    return () => clearInterval(timer);
  }, [pending]);

  useEffect(() => {
    if (settledCount === 0) return;
    (error ? errorRef.current : headingRef.current)?.focus();
  }, [settledCount]);

  async function handleAnalyze() {
    setPending(true);
    setError(null);
    onInProgressChange(
      { runId, resultIndex, requestName, phase: "waiting-for-ai", phaseStartedAt: new Date().toISOString() },
      true,
    );
    const result = await requestFailureAnalysis(collectionId, runId, resultIndex);
    setPending(false);
    if (!result.ok) {
      if (result.error === "failure_analysis_in_progress") {
        setError({ kind: "busy", message: "Another failure analysis is already running in this session." });
        const refreshed = await getFailureAnalysisInProgress();
        onInProgressChange(refreshed.ok ? refreshed.inProgress : null, false);
      } else {
        setError({ kind: "failed", message: result.message });
        onInProgressChange(null, true);
      }
      setSettledCount((count) => count + 1);
      return;
    }
    onInProgressChange(null, true);
    if (result.attempt.status === "analyzed") {
      onAnalysisChange(result.attempt.analysis);
    } else {
      // kept-previous: the stored explanation stands; say why the new one could not be written.
      onAnalysisChange(result.attempt.previousAnalysis);
      setError({ kind: "failed", message: result.attempt.message });
    }
    setSettledCount((count) => count + 1);
  }

  const busy = pending || inProgress !== null;

  return (
    <section
      aria-label={`AI failure analysis for ${requestName}`}
      data-testid="failure-analysis-panel"
      className="mt-3 space-y-3 rounded-md border border-border bg-surface p-3 text-sm text-slate-700 dark:text-slate-300"
    >
      <div className="flex flex-wrap items-center justify-between gap-2">
        <h4 className="text-xs font-semibold uppercase text-muted">AI failure analysis</h4>
        <button
          type="button"
          onClick={handleAnalyze}
          disabled={busy}
          aria-label={`${analysis ? "Analyze again" : "Analyze failure"}: ${requestName}`}
          className={analysis ? BUTTON_STYLES.secondary : BUTTON_STYLES.primary}
        >
          {analysis ? "Analyze again" : "Analyze failure"}
        </button>
      </div>

      <div aria-live="polite">
        {thisOne && inProgress && (
          <p className="flex flex-wrap items-center gap-2" data-testid="failure-analysis-progress">
            <span>{inProgress.phase === "waiting-for-ai" ? "Waiting for the local AI" : "Generating"}</span>
            <ElapsedTime key={inProgress.phase + inProgress.phaseStartedAt} since={inProgress.phaseStartedAt} />
          </p>
        )}
        {otherInProgress && inProgress && <p className="text-muted">Analyzing ‘{inProgress.requestName}’…</p>}
      </div>

      {error && (
        <div ref={errorRef} tabIndex={-1} className="focus:outline-none">
          <ErrorState message={error.message} testId="failure-analysis-error">
            {error.kind === "failed" && (
              <button type="button" onClick={handleAnalyze} disabled={busy} className={BUTTON_STYLES.secondary}>
                Try again
              </button>
            )}
          </ErrorState>
        </div>
      )}

      {analysis && <AnalysisView analysis={analysis} headingRef={headingRef} />}
    </section>
  );
}
