import type {
  ArtifactVariable,
  ExportResult,
  GenerationLimitation,
  PostmanCollection,
} from "@apipilot/shared-domain";
import { compareCodeUnits } from "./ordering";

/**
 * Renders the accompanying document (FR-016, FR-017) deterministically from the export result.
 * It states what the suite covers, what must be supplied to run it, and what could not be
 * expressed. It carries no request payload and no variable value (FR-025).
 */

const LIMITATION_HEADINGS: Record<GenerationLimitation["kind"], string> = {
  "no-expected-outcome": "Scenarios with no expected outcome",
  "undocumented-status-code": "Responses the specification did not document concretely",
  "unsupported-auth-scheme": "Authentication schemes this export cannot configure",
  "unsupported-content-type": "Request content types this export cannot represent",
  "unresolved-path-parameter": "Path parameters with no approved value",
  "specification-analysis-issue": "Operations carrying specification analysis issues",
  "alternative-auth-requirement-selected": "Operations declaring alternative authentication",
};

function coverageSection(collection: PostmanCollection, summary: ExportResult["summary"]): string[] {
  const lines = [
    "## Coverage",
    "",
    `- Requests: ${summary.requestCount}`,
    `- Folders: ${summary.folderCount}`,
    `- Rule-derived scenarios: ${summary.byProvenance.RULE}`,
    `- AI-derived scenarios: ${summary.byProvenance.AI}`,
    "",
    "Requests are organized into one folder per API grouping:",
    "",
  ];
  for (const folder of collection.item) {
    lines.push(`- \`${folder.name}\` — ${folder.item.length} request(s)`);
  }
  return lines;
}

function variableSection(variables: ArtifactVariable[]): string[] {
  const lines = [
    "## Variables to supply",
    "",
    "Fill these into the accompanying environment file before running. Credential variables are",
    "stored as secret values in the environment and never appear in the collection.",
    "",
    "| Variable | Credential | Purpose |",
    "| --- | --- | --- |",
  ];
  for (const variable of [...variables].sort((a, b) => compareCodeUnits(a.name, b.name))) {
    lines.push(`| \`${variable.name}\` | ${variable.secret ? "yes" : "no"} | ${variable.purpose} |`);
  }
  return lines;
}

function limitationSection(limitations: GenerationLimitation[]): string[] {
  const lines = ["## Known limitations", ""];
  if (limitations.length === 0) {
    lines.push("None recorded: every approved scenario was expressed in full.");
    return lines;
  }
  lines.push(
    "These are cases the export could not express fully. They are reported rather than filled in",
    "with an assumed value.",
    "",
  );
  const kinds = [...new Set(limitations.map((limitation) => limitation.kind))].sort(
    compareCodeUnits,
  );
  for (const kind of kinds) {
    const forKind = limitations.filter((limitation) => limitation.kind === kind);
    lines.push(`### ${LIMITATION_HEADINGS[kind]} (${forKind.length})`, "");
    for (const limitation of forKind) {
      const scenario = limitation.scenarioId ? ` (${limitation.scenarioId})` : "";
      lines.push(`- \`${limitation.location}\`${scenario}: ${limitation.message}`);
    }
    lines.push("");
  }
  return lines;
}

/** Renders the accompanying README markdown deterministically from the export result and declared variables. */
export function renderReadme(
  result: Omit<ExportResult, "readme">,
  variables: ArtifactVariable[],
): string {
  const lines = [
    `# ${result.collection.info.name}`,
    "",
    "Generated by ApiPilot from an approved test model. Every request here comes from a scenario a",
    "reviewer accepted; nothing in this export was produced by AI, and no request was executed to",
    "create it.",
    "",
    ...coverageSection(result.collection, result.summary),
    "",
    ...variableSection(variables),
    "",
    "## How to run",
    "",
    "1. Import `collection.json` and `environment.json` into Postman.",
    "2. Select the imported environment and fill in the variables listed above.",
    "3. Run the collection, or any individual request.",
    "",
    "Running the collection issues real requests to the address you supply. Generating this",
    "artifact is not authorization to run it: only run it against an environment you are",
    "authorized to call.",
    "",
    ...limitationSection(result.limitations),
    "## Validation",
    "",
    result.validation.valid
      ? "The generated collection passed ApiPilot's pre-delivery validation check."
      : "The generated collection did not pass validation and was not delivered.",
    "",
  ];
  return `${lines.join("\n")}`;
}