import { createHash } from "node:crypto";
import {
  FAILURE_RULE_DESCRIPTIONS,
  type FailureAnalysisConclusion,
  type FailureCause,
  type FailureEvidence,
  type InferenceRequest,
  type SpecificationContext,
  type SpecificationContextUnavailableReason,
} from "@apipilot/shared-domain";

/**
 * Versioned prompt for AP-031 failure analysis (specs/030-ai-failure-analysis research D6, D8,
 * D16; constitution XXIII). The feature owns its system instruction and sends it through
 * `InferenceRequest.systemPrompt`, so the provider stays free of feature rules. Since v4 the
 * model only explains a cause the rules already decided; it never chooses one (research D15).
 */

/**
 * Bump whenever the system prompt, task or answer format changes.
 * v2 (2026-09-23): three contrasting examples replaced v1's single, copied example.
 * v3 (2026-09-24): evaluated but never shipped (evaluation.md run 2).
 * v4 (2026-09-24): explanation only. The rule-decided cause is an input, and the placeholder answer
 * format carries no cause or confidence, because every evaluated model copied example values.
 */
export const FAILURE_ANALYSIS_RESPONSE_VERSION = 4;
/** Fits a 400-character summary and three short steps; about 46 s of decode at default planning rates (research D8). */
export const FAILURE_ANALYSIS_MAX_OUTPUT_TOKENS = 256;

/** The UI wording of each cause (data-model.md); the contradiction check (research D16) uses it too. */
export const FAILURE_CAUSE_LABELS: Readonly<Record<FailureCause, string>> = {
  "specification-mismatch": "Potential specification mismatch",
  "environment-issue": "Potential environment issue",
  "downstream-service-issue": "Potential downstream-service issue",
};

export const FAILURE_ANALYSIS_SYSTEM_PROMPT =
  "You explain why one API test request failed. Your entire response must be one complete valid " +
  "JSON object, starting with { and ending with }, with no markdown, backticks or commentary. Use " +
  "only the numbered evidence you are given and cite it by id. Never invent evidence ids, values, " +
  "endpoints or status codes.";

const TASK =
  "The likely cause of the failed request below has already been decided by fixed rules; it is " +
  "given in classification. Do not choose or name a different cause. Explain, using only the " +
  "evidence, what the evidence shows about this failure. If classification.cause is none, no rule " +
  "matched: explain what the evidence does and does not show, and suggest what evidence to gather. " +
  "Answer in the answerFormat shape: summary is under 300 characters; evidenceIds lists the " +
  "evidence ids you relied on; steps is an array of 1 to 3 short plain-text strings (not objects) " +
  "saying what to investigate next.";

const NO_RULE_MATCHED = "No rule matched the recorded evidence.";

/** Placeholders only: no concrete value a small model can copy into every answer (evaluation.md). */
const ANSWER_FORMAT = {
  responseVersion: FAILURE_ANALYSIS_RESPONSE_VERSION,
  summary: "<what the evidence shows about why this request failed>",
  evidenceIds: ["<id of each evidence item you relied on>"],
  steps: ["<what to investigate next, as plain text>"],
};

/**
 * SHA-256 of the fixed prompt text. A unit test recomputes it, so changing the prompt without also
 * bumping `FAILURE_ANALYSIS_RESPONSE_VERSION` and updating this value fails the build — keeping the
 * `responseVersion` recorded in provenance an exact identifier of the prompt (constitution XXIII).
 */
export const FAILURE_ANALYSIS_PROMPT_FINGERPRINT =
  "0e6e569267c494d28d0cd2509ca7411384ba423abc295670fcbfff4f6ff8b95a";

export function computeFailureAnalysisPromptFingerprint(): string {
  return createHash("sha256")
    .update(
      JSON.stringify({
        systemPrompt: FAILURE_ANALYSIS_SYSTEM_PROMPT,
        task: TASK,
        noRuleMatched: NO_RULE_MATCHED,
        causeLabels: FAILURE_CAUSE_LABELS,
        ruleDescriptions: FAILURE_RULE_DESCRIPTIONS,
        answerFormat: ANSWER_FORMAT,
      }),
    )
    .digest("hex");
}

const UNAVAILABLE_NOTE: Record<SpecificationContextUnavailableReason, string> = {
  "no-request-identity": "No specification context: this result was recorded before request identity was tracked.",
  "no-generated-collection": "No specification context: the session has no generated collection.",
  "not-generated-by-current-workflow":
    "No specification context: this request was not generated by the current guided workflow.",
  "no-originating-scenario": "No specification context: this request has no originating test scenario.",
};

function specificationContextNote(context: SpecificationContext): string {
  if (context.status === "unavailable") return UNAVAILABLE_NOTE[context.reason];
  return `Generated from ${context.operationMethod.toUpperCase()} ${context.operationPath}, scenario "${context.scenarioName}".`;
}

function classificationText(conclusion: FailureAnalysisConclusion): { cause: string; rule: string } {
  if (conclusion.kind === "insufficient-evidence") return { cause: "none", rule: NO_RULE_MATCHED };
  return { cause: FAILURE_CAUSE_LABELS[conclusion.cause], rule: FAILURE_RULE_DESCRIPTIONS[conclusion.ruleId] };
}

export interface FailureAnalysisPromptInput {
  requestMethod: string;
  requestName: string;
  /** The prompt copy of the evidence: possibly trimmed for the input budget, original ids kept (D8). */
  evidence: readonly FailureEvidence[];
  specificationContext: SpecificationContext;
  /** The rule-decided outcome the model must explain (research D15, D16). */
  conclusion: FailureAnalysisConclusion;
  /** Present only when evidence was omitted from this prompt to fit the input budget (D8). */
  note?: string;
}

export function buildFailureAnalysisPrompt(input: FailureAnalysisPromptInput): string {
  return JSON.stringify({
    responseVersion: FAILURE_ANALYSIS_RESPONSE_VERSION,
    task: TASK,
    request: { method: input.requestMethod.toUpperCase(), name: input.requestName },
    classification: classificationText(input.conclusion),
    evidence: input.evidence.map((item) => ({ id: item.id, text: item.text })),
    ...(input.note ? { note: input.note } : {}),
    specificationContextNote: specificationContextNote(input.specificationContext),
    answerFormat: ANSWER_FORMAT,
  });
}

/** Content-derived request id, as AP-005 does (`enhanceTestModel.ts`): never random (constitution XXIV). */
export function buildFailureAnalysisRequest(prompt: string): InferenceRequest {
  return {
    contractVersion: 1,
    requestId: `failure-${createHash("sha256").update(prompt).digest("hex").slice(0, 24)}`,
    input: prompt,
    expectedOutputFormat: "json",
    maxOutputTokens: FAILURE_ANALYSIS_MAX_OUTPUT_TOKENS,
    systemPrompt: FAILURE_ANALYSIS_SYSTEM_PROMPT,
  };
}
