import type {
  AssertionOutcome,
  FailureCategory,
  RawHeader,
  RawRequestCapture,
  RequestResult,
  TestScenario,
} from "@apipilot/shared-domain";
import { assertionTestPlan } from "../postman/assertionScripts";
import { isSensitiveFieldName } from "../testDesign/sensitiveValueDetection";

/**
 * Maps one Newman single-item run result to this feature's `RequestResult`/`FailureCategory`
 * vocabulary (research.md D5). Deliberately duck-typed against a minimal shape rather than
 * Newman's own `NewmanRunExecution` type: only the fields this mapping actually reads, so a test
 * can construct realistic fixtures without depending on Newman's (or `postman-collection`'s)
 * exact internal classes.
 */

export interface NewmanAssertionError {
  name: string;
  message: string;
}

export interface NewmanAssertionResult {
  assertion: string;
  skipped: boolean;
  error?: NewmanAssertionError;
}

/** Minimal shape of a `postman-collection` `HeaderList` — just enough to read entries out. */
export interface NewmanHeaderList {
  all(): Array<{ key: string; value: string; disabled?: boolean }>;
}

/** Minimal shape of a `postman-collection` `Request`, post-variable-resolution. */
export interface NewmanRequestLike {
  url?: { toString(): string };
  headers?: NewmanHeaderList;
  body?: { toString(): string };
}

export interface NewmanExecutionResult {
  request?: NewmanRequestLike;
  response?: { code?: number; responseTime?: number; headers?: NewmanHeaderList; text?(): string };
  /** Present only for a connection-level failure (refused, DNS, TLS, timeout) — no response was received. */
  requestError?: { code?: string; message?: string };
  assertions?: NewmanAssertionResult[];
}

function toRawHeaders(headers: NewmanHeaderList | undefined): RawHeader[] {
  return (headers?.all() ?? [])
    .filter((header) => !header.disabled)
    .map((header) => ({ key: header.key, value: header.value }));
}

/**
 * Builds the FR-017a raw capture from Newman's already-resolved request/response objects.
 * Callers gate this to `"local"`-tier runs only (`runExecution.ts`) — this function itself does
 * not know or care about the environment tier.
 */
/** Exported for reuse by `externalCollections/mapUploadedResult.ts` — raw-capture handling is source-agnostic (data-model.md). */
export function buildRawCapture(execution: NewmanExecutionResult): RawRequestCapture | undefined {
  if (!execution.request) return undefined;
  return {
    requestUrl: execution.request.url?.toString() ?? "",
    requestHeaders: toRawHeaders(execution.request.headers),
    requestBody: execution.request.body?.toString() || undefined,
    responseHeaders: toRawHeaders(execution.response?.headers),
    responseBody: execution.response?.text?.() || undefined,
  };
}

/** Exported for reuse by `externalCollections/mapUploadedResult.ts` (research.md D6) — not duplicated. */
export function isTimeoutError(error: { code?: string } | undefined): boolean {
  return error?.code === "ESOCKETTIMEDOUT" || error?.code === "ETIMEDOUT";
}

/**
 * The check itself could not run — as opposed to running and disagreeing with the response
 * (`assertion-failed`/`unexpected-status`). Newman surfaces this as a `JSONError` when a schema
 * check tries to parse a response body that is not valid JSON.
 */
function isEvaluationFailure(error: NewmanAssertionError): boolean {
  return error.name === "JSONError";
}

const GENERIC_SCHEMA_FAILURE_DETAIL =
  "The response body did not conform to the documented schema (a credential-like field name was involved; detail withheld).";

/**
 * Hardening pass (FR-017, constitution XX): schema-conformance failure messages are generated by
 * a third-party validator (ajv, via Newman) whose exact wording is outside this codebase's
 * control. Empirically its messages report only a field path and an expectation (e.g. "data.name
 * should be string"), never the field's actual value — but if the path itself names a field this
 * platform already treats as credential-like (reusing `sensitiveValueDetection.ts`'s existing
 * rules, the same ones AP-006/AP-007 redact against, so detection can never disagree between
 * review, export, and execution), the whole message is replaced rather than trusted verbatim.
 */
/** Exported for reuse by `externalCollections/mapUploadedResult.ts` (research.md D6) — not duplicated. */
export function redactIfSensitive(message: string): string {
  const mentionsSensitiveField = message
    .split(/\W+/)
    .some((word) => word.length > 0 && isSensitiveFieldName(word));
  return mentionsSensitiveField ? GENERIC_SCHEMA_FAILURE_DETAIL : message;
}

/**
 * A short, non-sensitive summary of why one assertion failed (FR-017, constitution XX). Never
 * echoes response body content: a JSON-parse failure is reported generically rather than
 * forwarding Newman's own message, which embeds a snippet of the unparseable body.
 */
function assertionDetail(
  type: "status-code" | "schema-conformance",
  expectedStatusCode: string | undefined,
  responseStatusCode: number | undefined,
  error: NewmanAssertionError,
): string {
  if (type === "status-code") {
    return `Expected status ${expectedStatusCode ?? "unspecified"}, got ${responseStatusCode ?? "no response"}.`;
  }
  if (error.name === "JSONError") {
    return "The response body could not be parsed as JSON, so schema conformance could not be evaluated.";
  }
  if (error.name === "AssertionError") {
    return redactIfSensitive(error.message);
  }
  return "The response body did not conform to the documented schema.";
}

function categorizeFailure(failing: AssertionOutcome[]): FailureCategory {
  if (failing.some((outcome) => outcome.type === "status-code" && outcome.outcome === "failed")) {
    return "unexpected-status";
  }
  if (failing.some((outcome) => outcome.type === "schema-conformance" && outcome.outcome === "failed")) {
    return "assertion-failed";
  }
  return "could-not-evaluate";
}

/**
 * @param captureRawDetails FR-017a (2026-09-20 amendment): the caller passes `true` only for a
 * `"local"`-tier run. When `false` (every other tier), no raw header/body data is ever read off
 * `execution`, let alone attached to the returned `RequestResult` — the omission happens here,
 * not just at render time.
 */
export function mapNewmanResult(
  scenario: TestScenario,
  execution: NewmanExecutionResult,
  startedAt: string,
  captureRawDetails = false,
): RequestResult {
  const base = {
    scenarioId: scenario.id,
    operationPath: scenario.operationPath,
    operationMethod: scenario.operationMethod,
    startedAt,
  };
  const rawCapture = captureRawDetails ? buildRawCapture(execution) : undefined;

  if (execution.requestError) {
    return {
      ...base,
      outcome: "failed",
      failureCategory: isTimeoutError(execution.requestError) ? "timeout" : "connectivity-failure",
      // specs/029-execution-gap-closure FR-008/FR-009: dispatched, but no response arrived.
      processingStage: "no-response",
      durationMs: 0,
      assertionOutcomes: [],
      rawCapture,
    };
  }

  const durationMs = execution.response?.responseTime ?? 0;
  const responseStatusCode = execution.response?.code;
  const plan = assertionTestPlan(scenario);

  const assertionOutcomes: AssertionOutcome[] = plan.map((entry, position) => {
    const result = execution.assertions?.[position];
    if (!result || result.skipped) {
      return { assertionIndex: entry.originalIndex, type: entry.assertion.type, outcome: "could-not-evaluate" };
    }
    if (!result.error) {
      return { assertionIndex: entry.originalIndex, type: entry.assertion.type, outcome: "passed" };
    }
    return {
      assertionIndex: entry.originalIndex,
      type: entry.assertion.type,
      outcome: isEvaluationFailure(result.error) ? "could-not-evaluate" : "failed",
      detail: assertionDetail(
        entry.assertion.type,
        entry.assertion.type === "status-code" ? entry.assertion.expectedStatusCode : undefined,
        responseStatusCode,
        result.error,
      ),
    };
  });

  const failing = assertionOutcomes.filter((outcome) => outcome.outcome !== "passed");
  if (failing.length === 0) {
    return {
      ...base,
      outcome: "passed",
      processingStage: "response-received",
      durationMs,
      responseStatusCode,
      assertionOutcomes,
      rawCapture,
    };
  }
  return {
    ...base,
    outcome: "failed",
    failureCategory: categorizeFailure(failing),
    processingStage: "response-received",
    durationMs,
    responseStatusCode,
    assertionOutcomes,
    rawCapture,
  };
}
