// ApiPilot k6 performance test, request-chain plan (AP-037, specs/037-request-chain-performance).
// Generated by ApiPilot from steps authored by the engineer and not verified by ApiPilot. Only the
// unmodified generated script runs from the plan. It contains no values: each value named in
// VALUE_ENV is read from that environment variable at run time.
// Plan fingerprint: dfc45b1b942e2fa455f1dd2c2d671a5a37d6fed41494cd4fd5a57b9f4256d251
import http from "k6/http";
import { check, sleep } from "k6";
import { Counter } from "k6/metrics";
import exec from "k6/execution";

export const options = {
  "stages": [
    {
      "duration": "60s",
      "target": 1
    }
  ],
  "systemTags": [
    "status",
    "method",
    "error_code",
    "check",
    "group"
  ]
};

const VALUE_ENV = {
  "baseUrl": "APIPILOT_V_0",
  "client_id": "APIPILOT_V_1",
  "client_secret": "APIPILOT_V_2"
};
const THINK_TIME_S = 1;
const DYNAMIC = {
  "apipilot_dyn_0": {
    "kind": "$randomFullName"
  },
  "apipilot_dyn_1": {
    "kind": "$randomEmail"
  }
};
const DATA_SETS = [];
const SETUP_STEPS = [
  {
    "id": "s1",
    "chain": "c1",
    "runs": "once-before-load",
    "method": "POST",
    "url": "{{baseUrl}}/auth/token",
    "query": [],
    "headers": [],
    "body": {
      "kind": "form",
      "fields": [
        {
          "name": "client_id",
          "value": "{{client_id}}"
        },
        {
          "name": "client_secret",
          "value": "{{client_secret}}"
        }
      ]
    },
    "expected": [
      "200"
    ],
    "extractors": [
      {
        "name": "token",
        "body": [
          "access_token"
        ]
      }
    ],
    "checks": [],
    "thinkS": null,
    "needs": [
      "baseUrl",
      "client_id",
      "client_secret"
    ],
    "uses": [],
    "columns": [],
    "refreshFrom": [],
    "readsBody": true
  }
];
const CHAINS = [
  {
    "id": "c1",
    "steps": [
      {
        "id": "s2",
        "chain": "c1",
        "runs": "every-iteration",
        "method": "POST",
        "url": "{{baseUrl}}/api/v1/customers",
        "query": [],
        "headers": [
          {
            "name": "Authorization",
            "value": "Bearer {{token}}"
          }
        ],
        "body": {
          "kind": "raw",
          "contentType": "application/json",
          "fill": "json",
          "text": "{\"name\":\"{{apipilot_dyn_0}}\",\"email\":\"{{apipilot_dyn_1}}\"}"
        },
        "expected": [
          "201"
        ],
        "extractors": [
          {
            "name": "customer_id",
            "body": [
              "id"
            ]
          }
        ],
        "checks": [],
        "thinkS": null,
        "needs": [
          "baseUrl"
        ],
        "uses": [
          "token"
        ],
        "columns": [],
        "refreshFrom": [
          "s1"
        ],
        "readsBody": true
      },
      {
        "id": "s3",
        "chain": "c1",
        "runs": "every-iteration",
        "method": "GET",
        "url": "{{baseUrl}}/api/v1/customers",
        "query": [
          {
            "name": "page",
            "value": "1"
          },
          {
            "name": "size",
            "value": "20"
          }
        ],
        "headers": [
          {
            "name": "Authorization",
            "value": "Bearer {{token}}"
          }
        ],
        "body": {
          "kind": "none"
        },
        "expected": [
          "200"
        ],
        "extractors": [],
        "checks": [],
        "thinkS": null,
        "needs": [
          "baseUrl"
        ],
        "uses": [
          "token"
        ],
        "columns": [],
        "refreshFrom": [
          "s1"
        ],
        "readsBody": false
      },
      {
        "id": "s4",
        "chain": "c1",
        "runs": "every-iteration",
        "method": "PUT",
        "url": "{{baseUrl}}/api/v1/customers/{{customer_id}}",
        "query": [],
        "headers": [
          {
            "name": "Authorization",
            "value": "Bearer {{token}}"
          }
        ],
        "body": {
          "kind": "raw",
          "contentType": "application/json",
          "fill": "json",
          "text": "{\"name\":\"Replaced\"}"
        },
        "expected": [
          "200"
        ],
        "extractors": [],
        "checks": [],
        "thinkS": null,
        "needs": [
          "baseUrl"
        ],
        "uses": [
          "customer_id",
          "token"
        ],
        "columns": [],
        "refreshFrom": [
          "s1"
        ],
        "readsBody": false
      },
      {
        "id": "s5",
        "chain": "c1",
        "runs": "every-iteration",
        "method": "GET",
        "url": "{{baseUrl}}/api/v1/customers/{{customer_id}}",
        "query": [],
        "headers": [
          {
            "name": "Authorization",
            "value": "Bearer {{token}}"
          }
        ],
        "body": {
          "kind": "none"
        },
        "expected": [
          "200"
        ],
        "extractors": [],
        "checks": [
          {
            "id": "k3",
            "kind": "field-equals",
            "path": [
              "id"
            ],
            "expected": {
              "type": "text",
              "value": "{{customer_id}}"
            }
          }
        ],
        "thinkS": null,
        "needs": [
          "baseUrl"
        ],
        "uses": [
          "customer_id",
          "token"
        ],
        "columns": [],
        "refreshFrom": [
          "s1"
        ],
        "readsBody": true
      },
      {
        "id": "s6",
        "chain": "c1",
        "runs": "every-iteration",
        "method": "PATCH",
        "url": "{{baseUrl}}/api/v1/customers/{{customer_id}}",
        "query": [],
        "headers": [
          {
            "name": "Authorization",
            "value": "Bearer {{token}}"
          }
        ],
        "body": {
          "kind": "raw",
          "contentType": "application/json",
          "fill": "json",
          "text": "{\"name\":\"Updated\"}"
        },
        "expected": [
          "200"
        ],
        "extractors": [],
        "checks": [],
        "thinkS": null,
        "needs": [
          "baseUrl"
        ],
        "uses": [
          "customer_id",
          "token"
        ],
        "columns": [],
        "refreshFrom": [
          "s1"
        ],
        "readsBody": false
      },
      {
        "id": "s7",
        "chain": "c1",
        "runs": "every-iteration",
        "method": "DELETE",
        "url": "{{baseUrl}}/api/v1/customers/{{customer_id}}",
        "query": [],
        "headers": [
          {
            "name": "Authorization",
            "value": "Bearer {{token}}"
          }
        ],
        "body": {
          "kind": "none"
        },
        "expected": [
          "204"
        ],
        "extractors": [],
        "checks": [],
        "thinkS": null,
        "needs": [
          "baseUrl"
        ],
        "uses": [
          "customer_id",
          "token"
        ],
        "columns": [],
        "refreshFrom": [
          "s1"
        ],
        "readsBody": false
      }
    ]
  }
];
const DATA = [];

const missingData = new Counter("apipilot_missing_data");
const notAttempted = new Counter("apipilot_not_attempted");
const cutShort = new Counter("apipilot_cut_short");
const tokenRefresh = new Counter("apipilot_token_refresh");
const captureOutcome = new Counter("apipilot_capture");
const checkOutcome = new Counter("apipilot_check");
const setupOutcome = new Counter("apipilot_setup");
const dataOutcome = new Counter("apipilot_data");
const REFERENCE = /\{\{([A-Za-z0-9_]+)\}\}/g;
const RUN_TAG_SETTING = __ENV.APIPILOT_RUN_TAG;
const RUN_TAG = typeof RUN_TAG_SETTING === "string" && /^[0-9a-f]{6}$/.test(RUN_TAG_SETTING) ? RUN_TAG_SETTING : "";
const FIRST_NAMES = ["Ada", "Alan", "Barbara", "Claude", "Dennis", "Donald", "Edsger", "Frances", "Grace", "Hedy", "Ivan", "Jean", "Ken", "Katherine", "Leslie", "Linus", "Margaret", "Niklaus", "Radia", "Rosalind", "Sophie", "Tim", "Vint", "Whitfield"];
const LAST_NAMES = ["Allen", "Babbage", "Backus", "Berners", "Cerf", "Diffie", "Dijkstra", "Engelbart", "Hamilton", "Hopper", "Johnson", "Kahn", "Knuth", "Lamarr", "Lamport", "Liskov", "Lovelace", "Perlman", "Ritchie", "Shannon", "Sutherland", "Thompson", "Turing", "Wirth"];
const ALPHANUMERIC = "0123456789abcdefghijklmnopqrstuvwxyz";
const SETUP_BY_ID = new Map();
for (const step of SETUP_STEPS) SETUP_BY_ID.set(step.id, step);
const COLUMNS = new Map();
for (let set = 0; set < DATA_SETS.length; set++) {
  const columns = DATA_SETS[set].columns;
  for (let column = 0; column < columns.length; column++) COLUMNS.set(columns[column], { set: set, column: column });
}

function env(name) {
  if (!Object.prototype.hasOwnProperty.call(VALUE_ENV, name)) return undefined;
  const value = __ENV[VALUE_ENV[name]];
  return value === undefined || value === "" ? undefined : value;
}

function hex(value, width) {
  let text = Number(value).toString(16);
  while (text.length < width) text = "0" + text;
  return text.slice(-width);
}

function mix(vu, iteration, k) {
  let h = Math.imul(vu ^ 0x9e3779b9, 0x85ebca6b) ^ Math.imul(iteration + 0x632be5ab, 0xc2b2ae35) ^ Math.imul(k + 0x27d4eb2f, 0x165667b1);
  h ^= h >>> 16;
  h = Math.imul(h, 0x85ebca6b);
  h ^= h >>> 13;
  h = Math.imul(h, 0xc2b2ae35);
  h ^= h >>> 16;
  return h >>> 0;
}

function dynamicValue(name) {
  const kind = DYNAMIC[name].kind;
  const k = Number(name.slice("apipilot_dyn_".length));
  const m = mix(__VU, __ITER, k);
  const first = FIRST_NAMES[m % FIRST_NAMES.length];
  const last = LAST_NAMES[Math.floor(m / FIRST_NAMES.length) % LAST_NAMES.length];
  const person = (first + "." + last).toLowerCase();
  if (kind === "$guid" || kind === "$randomUUID") {
    const tag = RUN_TAG === "" ? "000000" : RUN_TAG;
    return hex(__VU, 8) + "-" + hex(k, 4) + "-4" + tag.slice(0, 3) + "-8" + tag.slice(3) + "-" + hex(__ITER, 12);
  }
  if (kind === "$timestamp") return String(Math.floor(Date.now() / 1000));
  if (kind === "$isoTimestamp") return new Date(Date.now()).toISOString();
  if (kind === "$randomInt") return String(m % 1001);
  if (kind === "$randomFirstName") return first;
  if (kind === "$randomLastName") return last;
  if (kind === "$randomFullName") return first + " " + last;
  if (kind === "$randomUserName") return person + (RUN_TAG === "" ? "" : "_r" + RUN_TAG) + "_vu" + __VU + "_it" + __ITER + "_" + k;
  if (kind === "$randomEmail") return person + "+" + (RUN_TAG === "" ? "" : "r" + RUN_TAG + "-") + "vu" + __VU + "-it" + __ITER + "-" + k + "@example.com";
  if (kind === "$randomPhoneNumber") return String(200 + (m % 800)) + "-" + String(200 + (Math.floor(m / 800) % 800)) + "-" + String(10000 + (Math.floor(m / 640000) % 10000)).slice(1);
  if (kind === "$randomAlphaNumeric") return ALPHANUMERIC[m % ALPHANUMERIC.length];
  if (kind === "$randomBoolean") return m % 2 === 0 ? "true" : "false";
  return "";
}

function take(set, index) {
  const rows = DATA[set];
  if (rows.length === 0) return undefined;
  dataOutcome.add(1, { dataset: String(set), outcome: index >= rows.length ? "wrap" : "take" });
  return rows[index % rows.length];
}

function firstRows() {
  const rows = new Map();
  for (let set = 0; set < DATA_SETS.length; set++) {
    const all = DATA[set];
    if (all.length > 0) rows.set(set, all[0]);
  }
  return rows;
}

function resolve(name, scope) {
  if (scope.vars.has(name)) return scope.vars.get(name);
  if (Object.prototype.hasOwnProperty.call(DYNAMIC, name)) return dynamicValue(name);
  const column = COLUMNS.get(name);
  if (column !== undefined) {
    const row = scope.rows.get(column.set);
    if (row !== undefined) return row[+column.column];
  }
  const value = env(name);
  return value === undefined ? "" : value;
}

function fill(template, scope, mode) {
  return template.replace(REFERENCE, function (match, name) {
    const value = String(resolve(name, scope));
    if (mode === "url") return name === "baseUrl" ? value : encodeURIComponent(value);
    if (mode === "json") return JSON.stringify(value).slice(1, -1);
    return value;
  });
}

function build(step, scope) {
  let url = fill(step.url, scope, "url");
  const query = [];
  for (const row of step.query) query.push(encodeURIComponent(fill(row.name, scope, "raw")) + "=" + encodeURIComponent(fill(row.value, scope, "raw")));
  if (query.length > 0) url += "?" + query.join("&");
  const headers = {};
  let typed = false;
  for (const header of step.headers) {
    headers[header.name] = fill(header.value, scope, "raw");
    if (header.name.toLowerCase() === "content-type") typed = true;
  }
  let body = null;
  if (step.body.kind === "raw") {
    body = fill(step.body.text, scope, step.body.fill);
    if (!typed) headers["Content-Type"] = step.body.contentType;
  }
  if (step.body.kind === "form") {
    const pairs = [];
    for (const field of step.body.fields) pairs.push(encodeURIComponent(fill(field.name, scope, "raw")) + "=" + encodeURIComponent(fill(field.value, scope, "raw")));
    body = pairs.join("&");
    if (!typed) headers["Content-Type"] = "application/x-www-form-urlencoded";
  }
  return { method: step.method, url: url, headers: headers, body: body };
}

function field(response, path) {
  let value;
  try {
    value = response.json();
  } catch (error) {
    return { found: false, value: undefined };
  }
  for (const part of path) {
    if (value === null || typeof value !== "object") return { found: false, value: undefined };
    if (typeof part === "number" && !Array.isArray(value)) return { found: false, value: undefined };
    const name = String(part);
    let found = false;
    for (const [key, child] of Object.entries(value)) {
      if (key === name) {
        value = child;
        found = true;
        break;
      }
    }
    if (!found) return { found: false, value: undefined };
  }
  return { found: true, value: value };
}

function headerValue(response, name) {
  const headers = response.headers;
  if (headers === null || typeof headers !== "object") return undefined;
  for (const [key, value] of Object.entries(headers)) {
    if (key.toLowerCase() === name) return value;
  }
  return undefined;
}

function scalarText(value) {
  if (typeof value === "string") return value === "" ? undefined : value;
  if (typeof value === "number") return isFinite(value) ? String(value) : undefined;
  if (typeof value === "boolean") return String(value);
  return undefined;
}

function extracted(response, extractor) {
  if (extractor.header !== undefined) return scalarText(headerValue(response, extractor.header));
  return scalarText(field(response, extractor.body).value);
}

function statusOk(status, expected) {
  const text = String(status);
  for (const code of expected) {
    if (code.length === 3 && code.slice(1) === "XX" ? text.length === 3 && text[0] === code[0] : text === code) return true;
  }
  return false;
}

function passes(item, response, scope) {
  if (item.kind === "time-at-most") return response.timings.duration <= item.maxMs;
  if (item.kind === "body-contains") return typeof response.body === "string" && response.body.indexOf(item.text) >= 0;
  const found = field(response, item.path);
  if (item.kind === "field-exists") return found.found;
  if (!found.found) return false;
  const expected = item.expected;
  if (expected.type === "number") return typeof found.value === "number" && found.value === expected.value;
  if (expected.type === "boolean") return typeof found.value === "boolean" && found.value === expected.value;
  const actual = found.value === null ? undefined : scalarText(found.value);
  return actual !== undefined && actual === fill(expected.value, scope, "raw");
}

function runChecks(step, response, scope, tags) {
  for (const item of step.checks) {
    const outcome = { check: item.id, outcome: passes(item, response, scope) ? "passed" : "failed" };
    if (tags.step !== undefined) {
      outcome.step = tags.step;
      outcome.journey = tags.journey;
    } else outcome.setup_step = tags.setup_step;
    checkOutcome.add(1, outcome);
  }
}

function send(step, scope, tags) {
  const request = build(step, scope);
  return http.request(request.method, request.url, request.body, {
    headers: request.headers,
    tags: tags,
    responseType: step.readsBody ? "text" : "none",
  });
}

function sendSetup(step, scope, kind) {
  for (const name of step.needs) if (env(name) === undefined) return { values: [], failed: "missing-data:" + name, acquiredAtMs: Date.now(), lifetimeS: 0 };
  const response = send(step, scope, { apipilot_kind: kind, setup_step: step.id });
  if (response.status === 0) return { values: [], failed: "no-response", acquiredAtMs: Date.now(), lifetimeS: 0 };
  runChecks(step, response, scope, { setup_step: step.id });
  if (!statusOk(response.status, step.expected)) return { values: [], failed: "status", acquiredAtMs: Date.now(), lifetimeS: 0 };
  const values = [];
  for (const extractor of step.extractors) {
    const value = extracted(response, extractor);
    captureOutcome.add(1, { setup_step: step.id, capture: extractor.name, outcome: value === undefined ? "failed" : "ok" });
    if (value === undefined) return { values: [], failed: "extractor:" + extractor.name, acquiredAtMs: Date.now(), lifetimeS: 0 };
    values.push({ name: extractor.name, value: value });
  }
  const lifetime = Number(field(response, ["expires_in"]).value);
  return { values: values, failed: null, acquiredAtMs: Date.now(), lifetimeS: isFinite(lifetime) && lifetime > 0 ? lifetime : 0 };
}

export function setup() {
  const scope = { vars: new Map(), rows: firstRows() };
  const usedSets = new Set();
  const handed = [];
  for (const step of SETUP_STEPS) {
    for (const name of step.columns) {
      const column = COLUMNS.get(name);
      if (column !== undefined) usedSets.add(column.set);
    }
    const result = sendSetup(step, scope, "setup");
    if (result.failed !== null) {
      setupOutcome.add(1, { setup_step: step.id, outcome: "failed", reason: result.failed });
      exec.test.abort("apipilot: a once-before-load step failed");
    }
    setupOutcome.add(1, { setup_step: step.id, outcome: "ok", reason: "" });
    if (result.lifetimeS === 0 && step.extractors.length > 0) tokenRefresh.add(1, { setup_step: step.id, outcome: "no-lifetime" });
    for (const entry of result.values) scope.vars.set(entry.name, entry.value);
    handed.push({ id: step.id, values: result.values, acquiredAtMs: result.acquiredAtMs, lifetimeS: result.lifetimeS });
  }
  for (const set of usedSets) dataOutcome.add(1, { dataset: String(set), outcome: "setup" });
  return { setup: handed };
}

let vu = null;

function initVirtualUser(data) {
  vu = { setupValues: new Map(), setupState: new Map(), values: new Map(), done: new Set(), rows: new Map() };
  for (const entry of data.setup) {
    vu.setupState.set(entry.id, { values: entry.values, acquiredAtMs: entry.acquiredAtMs, lifetimeS: entry.lifetimeS });
    if (Array.isArray(entry.values)) for (const value of entry.values) vu.setupValues.set(value.name, value.value);
  }
  for (let set = 0; set < DATA_SETS.length; set++) {
    if (DATA_SETS[set].mode !== "row-per-virtual-user") continue;
    const row = take(set, exec.vu.idInTest - 1);
    if (row !== undefined) vu.rows.set(set, row);
  }
}

function refreshFraction() {
  return 0.7 + 0.01 * ((exec.vu.idInTest - 1) % 11);
}

function maybeRefresh(id, scope) {
  const state = vu.setupState.get(id);
  const step = SETUP_BY_ID.get(id);
  if (!state || !step || !Array.isArray(state.values) || !(state.lifetimeS > 0)) return;
  if (Date.now() - state.acquiredAtMs < state.lifetimeS * 1000 * refreshFraction()) return;
  const result = sendSetup(step, { vars: new Map(vu.setupValues), rows: firstRows() }, "token-refresh");
  if (result.failed === null) {
    vu.setupState.set(id, { values: result.values, acquiredAtMs: result.acquiredAtMs, lifetimeS: result.lifetimeS });
    for (const entry of result.values) {
      vu.setupValues.set(entry.name, entry.value);
      scope.vars.set(entry.name, entry.value);
    }
    tokenRefresh.add(1, { setup_step: id, outcome: "ok" });
  } else {
    state.acquiredAtMs = Date.now();
    tokenRefresh.add(1, { setup_step: id, outcome: "failed" });
  }
}

function pause(step) {
  const seconds = step.thinkS === null ? THINK_TIME_S : step.thinkS;
  if (seconds > 0) sleep(seconds);
}

function cut(chain, index, tags, capture) {
  cutShort.add(1, { step: tags.step, journey: tags.journey, capture: capture });
  for (const rest of chain.steps.slice(index + 1)) notAttempted.add(1, { step: rest.id, journey: chain.id, reason: "cut-short" });
}

function runChain(chain, scope) {
  for (let index = 0; index < chain.steps.length; index++) {
    const step = chain.steps[index];
    const tags = { step: step.id, journey: chain.id };
    const perUser = step.runs === "once-per-virtual-user";
    if (perUser && vu.done.has(step.id)) continue;
    const missing = step.needs.filter(function (name) {
      return env(name) === undefined;
    });
    if (missing.length > 0) {
      for (const name of missing) missingData.add(1, { step: step.id, journey: chain.id, variable: name });
      continue;
    }
    if (step.uses.some(function (name) { return !scope.vars.has(name); })) {
      notAttempted.add(1, { step: step.id, journey: chain.id, reason: "dependency" });
      continue;
    }
    for (const id of step.refreshFrom) maybeRefresh(id, scope);
    const response = send(step, scope, tags);
    const expected = statusOk(response.status, step.expected);
    check(response, { status: function () { return expected; } }, tags);
    runChecks(step, response, scope, tags);
    let failed = null;
    for (const extractor of step.extractors) {
      const value = expected ? extracted(response, extractor) : undefined;
      const ok = value !== undefined;
      check(response, { extraction: function () { return ok; } }, tags);
      captureOutcome.add(1, { step: step.id, journey: chain.id, capture: extractor.name, outcome: ok ? "ok" : "failed" });
      if (ok) {
        scope.vars.set(extractor.name, value);
        if (perUser) vu.values.set(extractor.name, value);
      } else if (failed === null) failed = extractor.name;
    }
    pause(step);
    if (failed !== null) {
      cut(chain, index, tags, failed);
      return;
    }
    if (perUser) {
      if (!expected) {
        cut(chain, index, tags, "");
        return;
      }
      vu.done.add(step.id);
    }
  }
}

export default function (data) {
  if (vu === null) initVirtualUser(data);
  const rows = new Map(vu.rows);
  for (let set = 0; set < DATA_SETS.length; set++) {
    if (DATA_SETS[set].mode !== "row-per-iteration") continue;
    const row = take(set, exec.scenario.iterationInTest);
    if (row !== undefined) rows.set(set, row);
  }
  const scope = { vars: new Map(), rows: rows };
  for (const [name, value] of vu.setupValues) scope.vars.set(name, value);
  for (const [name, value] of vu.values) scope.vars.set(name, value);
  for (const chain of CHAINS) runChain(chain, scope);
}
