// ApiPilot k6 performance test (AP-029, specs/031-k6-performance-testing).
// Generated by ApiPilot. Only the unmodified generated script runs from the performance plan;
// an edited copy can be run only as your own script in Run k6 Script (AP-034). It contains no
// values: each value named in VALUE_ENV is read from that environment variable at run time.
// Plan fingerprint: 972ff49a066d4df94759f0a9339b3911b261216e31cda38b77dc479f7dc954fa
import http from "k6/http";
import { check, sleep } from "k6";
import { Counter } from "k6/metrics";
import encoding from "k6/encoding";

export const options = {
  "stages": [
    {
      "duration": "60s",
      "target": 1
    }
  ],
  "systemTags": [
    "status",
    "method",
    "error_code",
    "check",
    "group"
  ]
};

const VALUE_ENV = {
  "baseUrl": "APIPILOT_V_0",
  "clientId": "APIPILOT_V_1",
  "clientSecret": "APIPILOT_V_2",
  "warehouseId": "APIPILOT_V_3"
};
const THINK_TIME_S = 0;
const UNIQUE = {
  "apipilot_unique_0": {
    "format": "email",
    "original": "user@example.com"
  }
};
const DYNAMIC = {};
const TOKEN_SOURCES = [
  {
    "scheme": "OrdersAuth",
    "kind": "oauth2-client-credentials",
    "request": {
      "method": "POST",
      "url": "{{baseUrl}}/oauth/token",
      "headers": [
        {
          "key": "Content-Type",
          "value": "application/x-www-form-urlencoded"
        }
      ],
      "auth": {
        "kind": "basic",
        "username": "{{clientId}}",
        "password": "{{clientSecret}}"
      },
      "body": "grant_type=client_credentials",
      "bodyKind": "text"
    },
    "needs": [
      "baseUrl",
      "clientId",
      "clientSecret"
    ],
    "captures": [
      {
        "key": "accessToken",
        "name": "accessToken",
        "source": {
          "body": [
            "access_token"
          ]
        }
      }
    ]
  }
];
const JOURNEYS = [
  {
    "id": "j_91a61d6ffd8b851b",
    "steps": [
      {
        "id": "s_f1faedcc7af8a36d",
        "operationKey": "POST /orders",
        "request": {
          "method": "POST",
          "url": "{{baseUrl}}/orders",
          "headers": [
            {
              "key": "Content-Type",
              "value": "application/json"
            }
          ],
          "auth": {
            "kind": "bearer",
            "token": "{{accessToken}}"
          },
          "body": "{\n  \"customerEmail\": \"{{apipilot_unique_0}}\",\n  \"quantity\": 1\n}",
          "bodyKind": "json"
        },
        "expected": [
          "201"
        ],
        "needs": [
          "baseUrl",
          "clientId",
          "clientSecret"
        ],
        "dependsOn": [],
        "captures": [
          {
            "key": "08990a6a9ecbc73665c27e863f6d395ad98167cf6353a62af54f5a170662387c_orderId",
            "name": "orderId",
            "source": {
              "body": [
                "orderId"
              ]
            }
          }
        ],
        "tokenSchemes": [
          "OrdersAuth"
        ]
      },
      {
        "id": "s_603b7f20fd6c66b0",
        "operationKey": "GET /orders/{orderId}",
        "request": {
          "method": "GET",
          "url": "{{baseUrl}}/orders/{{08990a6a9ecbc73665c27e863f6d395ad98167cf6353a62af54f5a170662387c_orderId}}",
          "headers": [],
          "auth": {
            "kind": "bearer",
            "token": "{{accessToken}}"
          }
        },
        "expected": [
          "200"
        ],
        "needs": [
          "baseUrl",
          "clientId",
          "clientSecret"
        ],
        "dependsOn": [
          "s_f1faedcc7af8a36d"
        ],
        "captures": [],
        "tokenSchemes": [
          "OrdersAuth"
        ]
      }
    ]
  },
  {
    "id": "j_d4b32c4864a14e16",
    "steps": [
      {
        "id": "s_34729e07a52aceaa",
        "operationKey": "GET /status",
        "request": {
          "method": "GET",
          "url": "{{baseUrl}}/status",
          "headers": [],
          "auth": {
            "kind": "bearer",
            "token": "{{accessToken}}"
          }
        },
        "expected": [
          "200"
        ],
        "needs": [
          "baseUrl",
          "clientId",
          "clientSecret"
        ],
        "dependsOn": [],
        "captures": [],
        "tokenSchemes": [
          "OrdersAuth"
        ]
      }
    ]
  },
  {
    "id": "j_997c7915ac4ca5ef",
    "steps": [
      {
        "id": "s_16fef0444660a0f5",
        "operationKey": "GET /warehouses/{warehouseId}",
        "request": {
          "method": "GET",
          "url": "{{baseUrl}}/warehouses/{{warehouseId}}",
          "headers": [],
          "auth": {
            "kind": "bearer",
            "token": "{{accessToken}}"
          }
        },
        "expected": [
          "200"
        ],
        "needs": [
          "baseUrl",
          "clientId",
          "clientSecret",
          "warehouseId"
        ],
        "dependsOn": [],
        "captures": [],
        "tokenSchemes": [
          "OrdersAuth"
        ]
      }
    ]
  }
];

const missingData = new Counter("apipilot_missing_data");
const notAttempted = new Counter("apipilot_not_attempted");
const cutShort = new Counter("apipilot_cut_short");
const tokenRefresh = new Counter("apipilot_token_refresh");
const captureOutcome = new Counter("apipilot_capture");
const REFERENCE = /\{\{([^{}]+)\}\}/g;
const RUN_TAG_SETTING = __ENV.APIPILOT_RUN_TAG;
const RUN_TAG = typeof RUN_TAG_SETTING === "string" && /^[0-9a-f]{6}$/.test(RUN_TAG_SETTING) ? RUN_TAG_SETTING : "";
const FIRST_NAMES = ["Ada", "Alan", "Barbara", "Claude", "Dennis", "Donald", "Edsger", "Frances", "Grace", "Hedy", "Ivan", "Jean", "Ken", "Katherine", "Leslie", "Linus", "Margaret", "Niklaus", "Radia", "Rosalind", "Sophie", "Tim", "Vint", "Whitfield"];
const LAST_NAMES = ["Allen", "Babbage", "Backus", "Berners", "Cerf", "Diffie", "Dijkstra", "Engelbart", "Hamilton", "Hopper", "Johnson", "Kahn", "Knuth", "Lamarr", "Lamport", "Liskov", "Lovelace", "Perlman", "Ritchie", "Shannon", "Sutherland", "Thompson", "Turing", "Wirth"];
const ALPHANUMERIC = "0123456789abcdefghijklmnopqrstuvwxyz";
const SOURCE_BY_SCHEME = {};
for (const source of TOKEN_SOURCES) SOURCE_BY_SCHEME[source.scheme] = source;

function env(name) {
  if (!Object.prototype.hasOwnProperty.call(VALUE_ENV, name)) return undefined;
  const value = __ENV[VALUE_ENV[name]];
  return value === undefined || value === "" ? undefined : value;
}

function hex(value, width) {
  let text = Number(value).toString(16);
  while (text.length < width) text = "0" + text;
  return text.slice(-width);
}

function uniqueValue(token) {
  const entry = UNIQUE[token];
  if (entry.format === "uuid") return hex(__VU, 8) + "-0000-4000-8000-" + hex(__ITER, 12);
  const at = entry.original.indexOf("@");
  const suffix = "+vu" + __VU + "-it" + __ITER;
  return at < 0 ? entry.original + suffix : entry.original.slice(0, at) + suffix + entry.original.slice(at);
}

function mix(vu, iteration, k) {
  let h = Math.imul(vu ^ 0x9e3779b9, 0x85ebca6b) ^ Math.imul(iteration + 0x632be5ab, 0xc2b2ae35) ^ Math.imul(k + 0x27d4eb2f, 0x165667b1);
  h ^= h >>> 16;
  h = Math.imul(h, 0x85ebca6b);
  h ^= h >>> 13;
  h = Math.imul(h, 0xc2b2ae35);
  h ^= h >>> 16;
  return h >>> 0;
}

function dynamicValue(name) {
  const kind = DYNAMIC[name].kind;
  const k = Number(name.slice("apipilot_dyn_".length));
  const m = mix(__VU, __ITER, k);
  const first = FIRST_NAMES[m % FIRST_NAMES.length];
  const last = LAST_NAMES[Math.floor(m / FIRST_NAMES.length) % LAST_NAMES.length];
  const person = (first + "." + last).toLowerCase();
  if (kind === "$guid" || kind === "$randomUUID") {
    const tag = RUN_TAG === "" ? "000000" : RUN_TAG;
    return hex(__VU, 8) + "-" + hex(k, 4) + "-4" + tag.slice(0, 3) + "-8" + tag.slice(3) + "-" + hex(__ITER, 12);
  }
  if (kind === "$timestamp") return String(Math.floor(Date.now() / 1000));
  if (kind === "$isoTimestamp") return new Date(Date.now()).toISOString();
  if (kind === "$randomInt") return String(m % 1001);
  if (kind === "$randomFirstName") return first;
  if (kind === "$randomLastName") return last;
  if (kind === "$randomFullName") return first + " " + last;
  if (kind === "$randomUserName") return person + (RUN_TAG === "" ? "" : "_r" + RUN_TAG) + "_vu" + __VU + "_it" + __ITER + "_" + k;
  if (kind === "$randomEmail") return person + "+" + (RUN_TAG === "" ? "" : "r" + RUN_TAG + "-") + "vu" + __VU + "-it" + __ITER + "-" + k + "@example.com";
  if (kind === "$randomPhoneNumber") return String(200 + (m % 800)) + "-" + String(200 + (Math.floor(m / 800) % 800)) + "-" + String(10000 + (Math.floor(m / 640000) % 10000)).slice(1);
  if (kind === "$randomAlphaNumeric") return ALPHANUMERIC[m % ALPHANUMERIC.length];
  if (kind === "$randomBoolean") return m % 2 === 0 ? "true" : "false";
  return "";
}

function resolve(name, scope) {
  if (scope.vars.has(name)) return scope.vars.get(name);
  if (scope.tokens.has(name)) return scope.tokens.get(name);
  if (Object.prototype.hasOwnProperty.call(DYNAMIC, name)) return dynamicValue(name);
  if (Object.prototype.hasOwnProperty.call(UNIQUE, name)) return uniqueValue(name);
  const value = env(name);
  return value === undefined ? "" : value;
}

function fill(template, scope, mode) {
  return template.replace(REFERENCE, function (match, name) {
    const value = String(resolve(name, scope));
    if (mode === "url") return name === "baseUrl" ? value : encodeURIComponent(value);
    if (mode === "json") return JSON.stringify(value).slice(1, -1);
    if (mode === "form") return encodeURIComponent(value);
    return value;
  });
}

function build(request, scope) {
  let url = fill(request.url, scope, "url");
  const headers = {};
  for (const header of request.headers) headers[fill(header.key, scope, "raw")] = fill(header.value, scope, "raw");
  const auth = request.auth;
  if (auth.kind === "bearer") headers.Authorization = "Bearer " + fill(auth.token, scope, "raw");
  if (auth.kind === "apikey" && auth.in === "header") headers[auth.key] = fill(auth.value, scope, "raw");
  if (auth.kind === "apikey" && auth.in === "query") url += (url.indexOf("?") < 0 ? "?" : "&") + encodeURIComponent(auth.key) + "=" + encodeURIComponent(fill(auth.value, scope, "raw"));
  if (auth.kind === "basic") {
    headers.Authorization = "Basic " + encoding.b64encode(fill(auth.username, scope, "raw") + ":" + fill(auth.password, scope, "raw"));
  }
  const bodyMode = request.bodyKind === "json" || request.bodyKind === "form" ? request.bodyKind : "raw";
  const body = request.body === undefined ? null : fill(request.body, scope, bodyMode);
  return { method: request.method, url: url, headers: headers, body: body };
}

function jsonField(response, path) {
  let value;
  try {
    value = response.json();
  } catch (error) {
    return undefined;
  }
  for (const part of path.split(".")) {
    if (value === null || typeof value !== "object") return undefined;
    let found = false;
    for (const [key, child] of Object.entries(value)) {
      if (key === part) {
        value = child;
        found = true;
        break;
      }
    }
    if (!found) return undefined;
  }
  return value;
}

function bodyValue(response, path) {
  let value;
  try {
    value = response.json();
  } catch (error) {
    return undefined;
  }
  for (const part of path) {
    if (value === null || typeof value !== "object") return undefined;
    if (typeof part === "number" && !Array.isArray(value)) return undefined;
    const name = String(part);
    let found = false;
    for (const [key, child] of Object.entries(value)) {
      if (key === name) {
        value = child;
        found = true;
        break;
      }
    }
    if (!found) return undefined;
  }
  return value;
}

function headerValue(response, name) {
  const headers = response.headers;
  if (headers === null || typeof headers !== "object") return undefined;
  for (const [key, value] of Object.entries(headers)) {
    if (key.toLowerCase() === name) return value;
  }
  return undefined;
}

function captured(response, source) {
  const value = source.header !== undefined ? headerValue(response, source.header) : bodyValue(response, source.body);
  if (typeof value === "string") return value === "" ? undefined : value;
  if (typeof value === "number") return isFinite(value) ? String(value) : undefined;
  if (typeof value === "boolean") return String(value);
  return undefined;
}

function statusOk(status, expected) {
  const text = String(status);
  for (const code of expected) {
    if (code.length === 3 && code.slice(1) === "XX" ? text.length === 3 && text[0] === code[0] : text === code) return true;
  }
  return false;
}

function acquire(source, kind, tokens) {
  for (const name of source.needs) if (env(name) === undefined) return { values: undefined, failed: null, acquiredAtMs: Date.now(), lifetimeS: 0 };
  const request = build(source.request, { vars: new Map(), tokens: tokens });
  const response = http.request(request.method, request.url, request.body, {
    headers: request.headers,
    tags: { apipilot_kind: kind },
    responseType: "text",
  });
  if (source.expected !== undefined && !statusOk(response.status, source.expected)) {
    return { values: undefined, failed: "", acquiredAtMs: Date.now(), lifetimeS: 0 };
  }
  const values = [];
  for (const capture of source.captures) {
    const value = captured(response, capture.source);
    if (value === undefined) return { values: undefined, failed: capture.name, acquiredAtMs: Date.now(), lifetimeS: 0 };
    values.push({ key: capture.key, value: value });
  }
  const lifetime = Number(jsonField(response, "expires_in"));
  return { values: values, failed: null, acquiredAtMs: Date.now(), lifetimeS: isFinite(lifetime) && lifetime > 0 ? lifetime : 0 };
}

export function setup() {
  const tokens = [];
  const acquired = new Map();
  for (const source of TOKEN_SOURCES) {
    const token = acquire(source, "token-setup", acquired);
    if (token.failed !== null && source.expected !== undefined) tokenRefresh.add(1, { outcome: "setup-failed", scheme: source.scheme, capture: token.failed });
    if (token.values !== undefined && token.lifetimeS === 0) tokenRefresh.add(1, { outcome: "no-lifetime", scheme: source.scheme });
    if (token.values !== undefined) for (const entry of token.values) acquired.set(entry.key, entry.value);
    tokens.push({ scheme: source.scheme, values: token.values, acquiredAtMs: token.acquiredAtMs, lifetimeS: token.lifetimeS });
  }
  return { tokens: tokens };
}

let vuTokens = null;

function refreshFraction() {
  return 0.7 + 0.01 * ((__VU - 1) % 11);
}

function maybeRefresh(scheme) {
  const current = vuTokens.get(scheme);
  const source = SOURCE_BY_SCHEME[scheme];
  if (!current || !source || !Array.isArray(current.values) || !(current.lifetimeS > 0)) return;
  if (Date.now() - current.acquiredAtMs < current.lifetimeS * 1000 * refreshFraction()) return;
  const next = acquire(source, "token-refresh", tokenScope());
  if (next.values !== undefined) {
    vuTokens.set(scheme, next);
    tokenRefresh.add(1, { outcome: "ok", scheme: scheme });
  } else {
    current.acquiredAtMs = Date.now();
    tokenRefresh.add(1, { outcome: "failed", scheme: scheme });
  }
}

function tokenScope() {
  const tokens = new Map();
  for (const source of TOKEN_SOURCES) {
    const token = vuTokens.get(source.scheme);
    for (const capture of source.captures) tokens.set(capture.key, "");
    if (token && Array.isArray(token.values)) for (const entry of token.values) tokens.set(entry.key, entry.value);
  }
  return tokens;
}

function runJourney(journey, run) {
  const scope = { vars: new Map(), tokens: new Map() };
  const unavailable = {};
  for (let index = 0; index < journey.steps.length; index++) {
    const step = journey.steps[index];
    const tags = { step: step.id, journey: journey.id };
    const missing = step.needs.filter(function (name) {
      return env(name) === undefined;
    });
    if (missing.length > 0) {
      for (const name of missing) missingData.add(1, { step: step.id, journey: journey.id, variable: name });
      unavailable[step.id] = true;
      continue;
    }
    if (step.dependsOn.some(function (id) { return unavailable[id]; })) {
      notAttempted.add(1, { step: step.id, journey: journey.id, reason: "dependency" });
      unavailable[step.id] = true;
      continue;
    }
    for (const scheme of step.tokenSchemes) maybeRefresh(scheme);
    scope.tokens = tokenScope();
    if (run.sent > 0 && THINK_TIME_S > 0) sleep(THINK_TIME_S);
    const request = build(step.request, scope);
    const response = http.request(request.method, request.url, request.body, {
      headers: request.headers,
      tags: tags,
      responseType: step.captures.length > 0 ? "text" : "none",
    });
    run.sent += 1;
    const expectedStatus = statusOk(response.status, step.expected);
    check(response, { status: function (r) { return statusOk(r.status, step.expected); } }, tags);
    let failedCapture = null;
    for (const capture of step.captures) {
      const value = expectedStatus ? captured(response, capture.source) : undefined;
      const ok = value !== undefined;
      check(response, { extraction: function () { return ok; } }, tags);
      captureOutcome.add(1, { step: step.id, journey: journey.id, capture: capture.name, outcome: ok ? "ok" : "failed" });
      if (ok) scope.vars.set(capture.key, value);
      else if (failedCapture === null) failedCapture = capture.name;
    }
    if (failedCapture !== null) {
      cutShort.add(1, { step: step.id, journey: journey.id, capture: failedCapture });
      for (const rest of journey.steps.slice(index + 1)) notAttempted.add(1, { step: rest.id, journey: journey.id, reason: "cut-short" });
      return;
    }
  }
}

export default function (data) {
  if (vuTokens === null) {
    vuTokens = new Map();
    for (const token of data.tokens) {
      vuTokens.set(token.scheme, { values: token.values, acquiredAtMs: token.acquiredAtMs, lifetimeS: token.lifetimeS });
    }
  }
  const run = { sent: 0 };
  for (const journey of JOURNEYS) runJourney(journey, run);
}
