// ApiPilot k6 performance test (AP-029, specs/031-k6-performance-testing).
// Generated by ApiPilot. Only the unmodified generated script runs from the performance plan;
// an edited copy can be run only as your own script in Run k6 Script (AP-034). It contains no
// values: each value named in VALUE_ENV is read from that environment variable at run time.
// Plan fingerprint: 972ff49a066d4df94759f0a9339b3911b261216e31cda38b77dc479f7dc954fa
import http from "k6/http";
import { check, sleep } from "k6";
import { Counter } from "k6/metrics";
import encoding from "k6/encoding";

export const options = {
  "stages": [
    {
      "duration": "60s",
      "target": 1
    }
  ],
  "systemTags": [
    "status",
    "method",
    "error_code",
    "check",
    "group"
  ]
};

const VALUE_ENV = {
  "baseUrl": "APIPILOT_V_0",
  "clientId": "APIPILOT_V_1",
  "clientSecret": "APIPILOT_V_2",
  "warehouseId": "APIPILOT_V_3"
};
const THINK_TIME_S = 0;
const UNIQUE = {
  "apipilot_unique_0": {
    "format": "email",
    "original": "user@example.com"
  }
};
const TOKEN_SOURCES = [
  {
    "scheme": "OrdersAuth",
    "kind": "oauth2-client-credentials",
    "tokenVariable": "accessToken",
    "request": {
      "method": "POST",
      "url": "{{baseUrl}}/oauth/token",
      "headers": [
        {
          "key": "Content-Type",
          "value": "application/x-www-form-urlencoded"
        }
      ],
      "auth": {
        "kind": "basic",
        "username": "{{clientId}}",
        "password": "{{clientSecret}}"
      },
      "body": "grant_type=client_credentials",
      "bodyKind": "text"
    },
    "responseField": "access_token",
    "needs": [
      "baseUrl",
      "clientId",
      "clientSecret"
    ]
  }
];
const JOURNEYS = [
  {
    "id": "j_91a61d6ffd8b851b",
    "steps": [
      {
        "id": "s_f1faedcc7af8a36d",
        "operationKey": "POST /orders",
        "request": {
          "method": "POST",
          "url": "{{baseUrl}}/orders",
          "headers": [
            {
              "key": "Content-Type",
              "value": "application/json"
            }
          ],
          "auth": {
            "kind": "bearer",
            "token": "{{accessToken}}"
          },
          "body": "{\n  \"customerEmail\": \"{{apipilot_unique_0}}\",\n  \"quantity\": 1\n}",
          "bodyKind": "json"
        },
        "expected": [
          "201"
        ],
        "needs": [
          "baseUrl",
          "clientId",
          "clientSecret"
        ],
        "dependsOn": [],
        "captures": [
          {
            "key": "08990a6a9ecbc73665c27e863f6d395ad98167cf6353a62af54f5a170662387c_orderId",
            "name": "orderId",
            "source": {
              "body": [
                "orderId"
              ]
            }
          }
        ],
        "tokenScheme": "OrdersAuth"
      },
      {
        "id": "s_603b7f20fd6c66b0",
        "operationKey": "GET /orders/{orderId}",
        "request": {
          "method": "GET",
          "url": "{{baseUrl}}/orders/{{08990a6a9ecbc73665c27e863f6d395ad98167cf6353a62af54f5a170662387c_orderId}}",
          "headers": [],
          "auth": {
            "kind": "bearer",
            "token": "{{accessToken}}"
          }
        },
        "expected": [
          "200"
        ],
        "needs": [
          "baseUrl",
          "clientId",
          "clientSecret"
        ],
        "dependsOn": [
          "s_f1faedcc7af8a36d"
        ],
        "captures": [],
        "tokenScheme": "OrdersAuth"
      }
    ]
  },
  {
    "id": "j_d4b32c4864a14e16",
    "steps": [
      {
        "id": "s_34729e07a52aceaa",
        "operationKey": "GET /status",
        "request": {
          "method": "GET",
          "url": "{{baseUrl}}/status",
          "headers": [],
          "auth": {
            "kind": "bearer",
            "token": "{{accessToken}}"
          }
        },
        "expected": [
          "200"
        ],
        "needs": [
          "baseUrl",
          "clientId",
          "clientSecret"
        ],
        "dependsOn": [],
        "captures": [],
        "tokenScheme": "OrdersAuth"
      }
    ]
  },
  {
    "id": "j_997c7915ac4ca5ef",
    "steps": [
      {
        "id": "s_16fef0444660a0f5",
        "operationKey": "GET /warehouses/{warehouseId}",
        "request": {
          "method": "GET",
          "url": "{{baseUrl}}/warehouses/{{warehouseId}}",
          "headers": [],
          "auth": {
            "kind": "bearer",
            "token": "{{accessToken}}"
          }
        },
        "expected": [
          "200"
        ],
        "needs": [
          "baseUrl",
          "clientId",
          "clientSecret",
          "warehouseId"
        ],
        "dependsOn": [],
        "captures": [],
        "tokenScheme": "OrdersAuth"
      }
    ]
  }
];

const missingData = new Counter("apipilot_missing_data");
const notAttempted = new Counter("apipilot_not_attempted");
const cutShort = new Counter("apipilot_cut_short");
const tokenRefresh = new Counter("apipilot_token_refresh");
const captureOutcome = new Counter("apipilot_capture");
const REFERENCE = /\{\{([^{}]+)\}\}/g;
const SOURCE_BY_SCHEME = {};
for (const source of TOKEN_SOURCES) SOURCE_BY_SCHEME[source.scheme] = source;

function env(name) {
  if (!Object.prototype.hasOwnProperty.call(VALUE_ENV, name)) return undefined;
  const value = __ENV[VALUE_ENV[name]];
  return value === undefined || value === "" ? undefined : value;
}

function hex(value, width) {
  let text = Number(value).toString(16);
  while (text.length < width) text = "0" + text;
  return text.slice(-width);
}

function uniqueValue(token) {
  const entry = UNIQUE[token];
  if (entry.format === "uuid") return hex(__VU, 8) + "-0000-4000-8000-" + hex(__ITER, 12);
  const at = entry.original.indexOf("@");
  const suffix = "+vu" + __VU + "-it" + __ITER;
  return at < 0 ? entry.original + suffix : entry.original.slice(0, at) + suffix + entry.original.slice(at);
}

function resolve(name, scope) {
  if (scope.vars.has(name)) return scope.vars.get(name);
  if (scope.tokens.has(name)) return scope.tokens.get(name);
  if (Object.prototype.hasOwnProperty.call(UNIQUE, name)) return uniqueValue(name);
  const value = env(name);
  return value === undefined ? "" : value;
}

function fill(template, scope, mode) {
  return template.replace(REFERENCE, function (match, name) {
    const value = String(resolve(name, scope));
    if (mode === "url") return name === "baseUrl" ? value : encodeURIComponent(value);
    if (mode === "json") return JSON.stringify(value).slice(1, -1);
    return value;
  });
}

function build(request, scope) {
  let url = fill(request.url, scope, "url");
  const headers = {};
  for (const header of request.headers) headers[fill(header.key, scope, "raw")] = fill(header.value, scope, "raw");
  const auth = request.auth;
  if (auth.kind === "bearer") headers.Authorization = "Bearer " + fill(auth.token, scope, "raw");
  if (auth.kind === "apikey" && auth.in === "header") headers[auth.key] = fill(auth.value, scope, "raw");
  if (auth.kind === "apikey" && auth.in === "query") url += (url.indexOf("?") < 0 ? "?" : "&") + encodeURIComponent(auth.key) + "=" + encodeURIComponent(fill(auth.value, scope, "raw"));
  if (auth.kind === "basic") {
    headers.Authorization = "Basic " + encoding.b64encode(fill(auth.username, scope, "raw") + ":" + fill(auth.password, scope, "raw"));
  }
  const body = request.body === undefined ? null : fill(request.body, scope, request.bodyKind === "json" ? "json" : "raw");
  return { method: request.method, url: url, headers: headers, body: body };
}

function jsonField(response, path) {
  let value;
  try {
    value = response.json();
  } catch (error) {
    return undefined;
  }
  for (const part of path.split(".")) {
    if (value === null || typeof value !== "object") return undefined;
    let found = false;
    for (const [key, child] of Object.entries(value)) {
      if (key === part) {
        value = child;
        found = true;
        break;
      }
    }
    if (!found) return undefined;
  }
  return value;
}

function bodyValue(response, path) {
  let value;
  try {
    value = response.json();
  } catch (error) {
    return undefined;
  }
  for (const part of path) {
    if (value === null || typeof value !== "object") return undefined;
    if (typeof part === "number" && !Array.isArray(value)) return undefined;
    const name = String(part);
    let found = false;
    for (const [key, child] of Object.entries(value)) {
      if (key === name) {
        value = child;
        found = true;
        break;
      }
    }
    if (!found) return undefined;
  }
  return value;
}

function headerValue(response, name) {
  const headers = response.headers;
  if (headers === null || typeof headers !== "object") return undefined;
  for (const [key, value] of Object.entries(headers)) {
    if (key.toLowerCase() === name) return value;
  }
  return undefined;
}

function captured(response, source) {
  const value = source.header !== undefined ? headerValue(response, source.header) : bodyValue(response, source.body);
  if (typeof value === "string") return value === "" ? undefined : value;
  if (typeof value === "number") return isFinite(value) ? String(value) : undefined;
  if (typeof value === "boolean") return String(value);
  return undefined;
}

function statusOk(status, expected) {
  const text = String(status);
  for (const code of expected) {
    if (code.length === 3 && code.slice(1) === "XX" ? text.length === 3 && text[0] === code[0] : text === code) return true;
  }
  return false;
}

function acquire(source, kind) {
  for (const name of source.needs) if (env(name) === undefined) return { value: undefined, acquiredAtMs: Date.now(), lifetimeS: 0 };
  const request = build(source.request, { vars: new Map(), tokens: new Map() });
  const response = http.request(request.method, request.url, request.body, {
    headers: request.headers,
    tags: { apipilot_kind: kind },
    responseType: "text",
  });
  const value = jsonField(response, source.responseField);
  const lifetime = Number(jsonField(response, "expires_in"));
  return {
    value: value === undefined || value === null || value === "" ? undefined : String(value),
    acquiredAtMs: Date.now(),
    lifetimeS: isFinite(lifetime) && lifetime > 0 ? lifetime : 0,
  };
}

export function setup() {
  const tokens = [];
  for (const source of TOKEN_SOURCES) {
    const token = acquire(source, "token-setup");
    if (token.value !== undefined && token.lifetimeS === 0) tokenRefresh.add(1, { outcome: "no-lifetime", scheme: source.scheme });
    tokens.push({ scheme: source.scheme, value: token.value, acquiredAtMs: token.acquiredAtMs, lifetimeS: token.lifetimeS });
  }
  return { tokens: tokens };
}

let vuTokens = null;

function refreshFraction() {
  return 0.7 + 0.01 * ((__VU - 1) % 11);
}

function maybeRefresh(scheme) {
  const current = vuTokens.get(scheme);
  const source = SOURCE_BY_SCHEME[scheme];
  if (!current || !source || current.value === undefined || !(current.lifetimeS > 0)) return;
  if (Date.now() - current.acquiredAtMs < current.lifetimeS * 1000 * refreshFraction()) return;
  const next = acquire(source, "token-refresh");
  if (next.value !== undefined) {
    vuTokens.set(scheme, next);
    tokenRefresh.add(1, { outcome: "ok", scheme: scheme });
  } else {
    current.acquiredAtMs = Date.now();
    tokenRefresh.add(1, { outcome: "failed", scheme: scheme });
  }
}

function tokenScope() {
  const tokens = new Map();
  for (const source of TOKEN_SOURCES) {
    const token = vuTokens.get(source.scheme);
    tokens.set(source.tokenVariable, token && token.value !== undefined ? token.value : "");
  }
  return tokens;
}

function runJourney(journey, run) {
  const scope = { vars: new Map(), tokens: new Map() };
  const unavailable = {};
  for (let index = 0; index < journey.steps.length; index++) {
    const step = journey.steps[index];
    const tags = { step: step.id, journey: journey.id };
    const missing = step.needs.filter(function (name) {
      return env(name) === undefined;
    });
    if (missing.length > 0) {
      for (const name of missing) missingData.add(1, { step: step.id, journey: journey.id, variable: name });
      unavailable[step.id] = true;
      continue;
    }
    if (step.dependsOn.some(function (id) { return unavailable[id]; })) {
      notAttempted.add(1, { step: step.id, journey: journey.id, reason: "dependency" });
      unavailable[step.id] = true;
      continue;
    }
    if (step.tokenScheme) maybeRefresh(step.tokenScheme);
    scope.tokens = tokenScope();
    if (run.sent > 0 && THINK_TIME_S > 0) sleep(THINK_TIME_S);
    const request = build(step.request, scope);
    const response = http.request(request.method, request.url, request.body, {
      headers: request.headers,
      tags: tags,
      responseType: step.captures.length > 0 ? "text" : "none",
    });
    run.sent += 1;
    const expectedStatus = statusOk(response.status, step.expected);
    check(response, { status: function (r) { return statusOk(r.status, step.expected); } }, tags);
    let failedCapture = null;
    for (const capture of step.captures) {
      const value = expectedStatus ? captured(response, capture.source) : undefined;
      const ok = value !== undefined;
      check(response, { extraction: function () { return ok; } }, tags);
      captureOutcome.add(1, { step: step.id, journey: journey.id, capture: capture.name, outcome: ok ? "ok" : "failed" });
      if (ok) scope.vars.set(capture.key, value);
      else if (failedCapture === null) failedCapture = capture.name;
    }
    if (failedCapture !== null) {
      cutShort.add(1, { step: step.id, journey: journey.id, capture: failedCapture });
      for (const rest of journey.steps.slice(index + 1)) notAttempted.add(1, { step: rest.id, journey: journey.id, reason: "cut-short" });
      return;
    }
  }
}

export default function (data) {
  if (vuTokens === null) {
    vuTokens = new Map();
    for (const token of data.tokens) {
      vuTokens.set(token.scheme, { value: token.value, acquiredAtMs: token.acquiredAtMs, lifetimeS: token.lifetimeS });
    }
  }
  const run = { sent: 0 };
  for (const journey of JOURNEYS) runJourney(journey, run);
}
